### ISSUE TITLE
Test suite is broken

### ISSUE THREAD

**Issue by DominikTo** [fruux/sabre-vobject#238]
With latest master it's currently impossible to run the test suite.

Fails with:
```
phpunit --configuration tests/phpunit.xml
Hoa main file (Core.php) must be included once.
```

Problem only appears when using phpunit, that is installed [globally](https://phpunit.de/manual/current/en/installation.html) via `composer global require "phpunit/phpunit=4.7.*"`[1].
Running `bin/phpunit --configuration tests/phpunit.xml` works fine.

Once `"hoa/bench"       : "~2.15.05.29"` is removed from `require-dev` in `composer.json` the phpunit version installed via `composer global` also works fine.

**Comment by evert** [comment]
This is actually an issue for @Hywan 

I would like to keep the ability for people to just run `phpunit` as a globally installed binary, unfortunately this is now broken if Hoa\Core is installed both globally and within the project. Both the phpunit and composer projects themselves had issues like this, but for each of them it was important enough to fix this problem.

The question is: is it important for Hoa to fix this as well? Alternatively, is `Hoa\Core` really needed as a dependency?

I can see that @Hywan does not consider this a bug though. If he doesn't, I think we should just remove `hoa/bench` from our composer.json. There's going to be a very small amount of people that will use it anyway (probably just me), so it's worth fixing.

But there's a workaround for @DominikTo , you can just run `bin/phpunit`.

**Comment by Hywan** [comment]
Composer introduces (natural) conflicts when we have stuff installed globally and locally. I have troubles with other projects, not only with Hoa. I am thinking of dropping the `files` property of the `composer.json` file of `Hoa\Core` though, because people encounter errors with this. Hoa is not responsible, but this does not fit to **some** workflow (even if it fits perfectly to 99.5% of other workflows…).

I consider running `phpunit` globally as an error. You must run `bin/phpunit` because it's a dependency. You will meet equivalent errors with C or Python shared libraries for instance. Always use local distributions and binaries, that's the rule.

Also, I don't care if we drop `Hoa\Bench`. I wasn't even aware that `sabre/vobject` were using it :yum:!

**Comment by evert** [comment]
It definitely makes sense, and I know Hoa is not the only project that has/had problems with this.

For me it's important that we don't have to change how people work with this. So the real question for me, are you willing to make this change, or should we remove the dependency.

I won't remove the code that uses Hoa\Bench though, but I'm ok with forcing myself to manually add the dependency whenever I need it. We used Hoa\Bench in the past for benchmarking, but I only very recently added it to `require-dev`, which is when this error started appearing.

**Comment by Hywan** [comment]
Consider I will work on it as soon as possible :-).

**Comment by Hywan** [comment]
Please open an issue on `Hoa\Core` too (thanks :-)).

**Comment by evert** [comment]
Awesome to hear =) Will do this a bit later this afternoon.

**Comment by evert** [comment]
Reported upstream.

**Comment by evert** [comment]
It looks like this has been fixed!

**Comment by evert** [comment]
I was mistaken. This is still an issue. I'm going to move `Hoa/Bench` from `require-dev` to `suggests`.
