### ISSUE TITLE
Timezone floating datetime

### ISSUE THREAD

**Issue by mail2rvg** [fruux/sabre-vobject#260]
Hi there,

we're experiencing some problems dealing timezones with floating date times. A floating datetime is described as (according RFC):

-----

"The date with local time form is simply a date-time value that does not contain the UTC designator nor does it reference a time zone. For example, the following represents Janurary 18, 1998, at 11 PM:

DTSTART:19980118T230000

Date-time values of this type are said to be "floating" and are not bound to any time zone in particular. They are used to represent the same hour, minute, and second value regardless of which time zone is currently being observed. For example, an event can be defined that indicates that an individual will be busy from 11:00 AM to 1:00 PM every day, no matter which time zone the person is in."

-----

When parsing the attached vCalendar object, calling the getDateTime method at the DTSTART  object returns a DateTime object with timezone UTC. According the method date_default_timezone_get our default timezone is Europe/Amsterdam and not UTC. 

Can anyone explain why I received a UTC datetime object, I doubt if this is correct.

![vcal](https://cloud.githubusercontent.com/assets/4534627/10636318/71102c30-77ff-11e5-8228-fb02275757c7.png)

**Comment by evert** [comment]
sabre/vobject does not use data_default_timezone, because we think it's a bad practice to rely on global values. Small bugs can creep in, so our default will always be UTC.

However, when you call `getDateTime`, you can actually pass a reference timezone as the first (and only) argument. This timezone will be used for floating dates and times:

https://github.com/fruux/sabre-vobject/blob/master/lib/Property/ICalendar/DateTime.php#L147

**Comment by mail2rvg** [comment]
Thanks for your fast answer. Do we need to pass the timezone if isFloating returns true or can we always pass the timezone?

**Comment by evert** [comment]
You can always pass the timezone. It's only used for floating times.
