### ISSUE TITLE
Create property annotations for objects

### ISSUE THREAD

**Issue by mburtscher** [fruux/sabre-vobject#285]
Your examples suggest using magic setters to set property values on objects:

```php
$card = new VCard();
$card->FN = "John Doe";
```

But those properties are not documented in code. You have to read your documentation or the RFC while developing to find the properties you wanna use.

I'd suggest adding `@property` annotations to ease use of the different object classes (http://phpdoc.org/docs/latest/references/phpdoc/tags/property.html).

**Comment by evert** [comment]
This was brought up earlier in #234 

There's a lot of problems with it though:

* In that PR many properties were incorrect in that context. Not every component can have any property.
* Also, properties can often be specified as strings or arrays when setting them. The PR suggest that they _have_ to be their respective components which is only usually true when getting them.
* Many properties can actually be of a different class when the `VALUE` parameter is specified.
* Also keep in mind that you can basically set *any* property, not just the ones from the RFC's. The RFC properties are just the standard ones.

And lastly, it will be quite frustrating to maintain such a massive list. If you have ideas on how to solve this better, I would love to hear it.

To me it's just a bit of a frustrating exercise. I don't really see the benefit because I don't use IDE's that take advantage of this. However, I can be persuaded if you have a great approach to tackling this problem =)

**Comment by evert** [comment]
No response received. Closing this until there's a better suggested approach.
