### ISSUE TITLE
"Unsupported CHARSET: utf-8" when parsing property

### ISSUE THREAD

**Issue by steffenweber** [fruux/sabre-vobject#288]
Reduced test case:
```
BEGIN:VCALENDAR
PRODID:Microsoft Windows Phone
VERSION:2.0
BEGIN:VEVENT
SUMMARY;CHARSET=utf-8:Foo
END:VEVENT
END:VCALENDAR
```

Parsing this file using `VObject\Reader::read` causes an exception to be thrown:
```
Fatal error: Uncaught exception 'Sabre\VObject\ParseException' with message 'Unsupported CHARSET: utf-8' in vendor/sabre/vobject/lib/Parser/MimeDir.php:476
```

I'm not sure whether it is the correct way to fix this but applying `strtoupper()` to `$charset` in `MimeDir.php:464` solves the problem for me.

I'm using sabre/vobject 4.0.1.

**Comment by DominikTo** [comment]
I added a unit test in a820f54b520bffcb2c104fc10f648a325eb80375.
Simply using `strtoupper()` won't be enough here I guess. That would break for [Windows-1252](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L62).

Not quite sure, if we only have to fix this in [`readProperty()`](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L466), or also in [`setCharset()`](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L106).

/cc @evert

**Comment by staabm** [comment]
maybe we should just do `strcasecmp` instead of a switch case with fixed values

**Comment by DominikTo** [comment]
That would be an option.

If we also want to support different case for [`setCharset()`](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L106) e.g. [setCharset('windows-1252')](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L106) we'd have to set the value of the match in [`$SUPPORTED_CHARSETS`](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L59) in [L111](https://github.com/fruux/sabre-vobject/blob/a820f54b520bffcb2c104fc10f648a325eb80375/lib/Parser/MimeDir.php#L111) instead of the value of the input (if we want to use the 'right' case internally).

**Comment by staabm** [comment]
my personal opinion: the programmatic api part should be strict, but the parsing part could still be forgiving

**Comment by evert** [comment]
Interestingly the `CHARSET` parameter does not exist in iCalendar 2.0. We're just picking it up because it's supported in vCard 2.1 and I assumed (falsely) that it wouldn't appear anywhere else.

To respond to strictness and the 'right' case, there is actually no register for these CHARSET values. If we assume that the CHARSET used here is identical to CHARSET in vCard 2.1, well, there's no list anywhere that we must follow or support.

So the _most correct_ way of fixing this, is completely ignoring the parameter. This is a good solution if we assume that windows phone (or others) don't send us character sets other than UTF-8. For windows phone I would say that this is a safe assumption, considering it's a fairly new platform.

So instead I'll add a check that causes us to _only_ consider `CHARSET` if we're currently parsing a vCard. Hopefully we don't run into iCalendar objects in the future that use `CHARSET` and are not encoded as `UTF-8`.

**Comment by DominikTo** [comment]
I am not 100% sure right now, but IIRC we have seen iCalendar objects that had inline charsets other than UTF-8. 🙈

**Comment by evert** [comment]
Yea that's possible, but the common case for iCalendar is that it's not specified inline like this. Instead, the information will usually be in some kind mime header.

In general I rather not create cases for situations we don't yet have proof for. Once the proof arrives we can change it again.

**Comment by evert** [comment]
I ran a scan of our vCards and found the following values for `CHARSET`:

* `UTF-8`
* `utf-8`
* `ISO-8859-1`
* `LATIN1`
* `ISO-8859-2`
* `Windows-1252`
* `iso-8859-2`
* `iso-8859-9`
* `SHIFT_JIS`
* `gb2312`

What's interesting though is that I actually _only_ looked at the vcards in our system, which only supports vcard 3 and 4. neither of which actually have the `CHARSET` parameter.



For iCalendar I've found the following:

* `UTF-8`
* `utf-8`
* `MacRoman`
* `ISO-8859-1`

Much less diversity...

So I  feel that we should disable `CHARSET` altogether for all formats except vCard 2.1, because it's literally the only one that actually has a `CHARSET` parameter.

Then later on if people run into issues, they can always open tickets for these. Really the primary use-case of supporting `CHARSET` _was_ for common vCard 2.1 blobs. I just had not anticipated that they might appear elsewhere.

And this also solves OP's issue in the most correct way. Ignoring `CHARSET` is what we should have done, and we should probably even 'repair' the object by removing the parameter, but we're not really doing that kind of stuff yet.

**Comment by evert** [comment]
Fixed in 581ed6c6da37dfbaebd211dd1784524d7c5c35e5

**Comment by steffenweber** [comment]
Thanks!

**Comment by simensen** [comment]
What is the solution here for Outlook using lowercase utf-8 then? It looks like this fix doesn't address that issue.

**Comment by evert** [comment]
@simensen , the ultimate fix for outlook using `CHARSET` in iCalendar was to ignore it. `CHARSET` is only a thing in vCard 2.1, so for every other format it's now no longer considered.

**Comment by simensen** [comment]
@evert Huh. We've just received a vCard 2.1 file from someone and we ran into a problem with newlines (see [this discussion](https://groups.google.com/forum/#!topic/sabredav-discuss/xvZ1-cL99A4)). We changed options to `1` but we still got the error about invalid format. We changed options to `2` and we no longer saw that message but we started getting the UTF-8 being unsupported message.

I'm up for just ignoring it but I'm not sure how I would do that. :-/ Is there another option to set somewhere?

**Comment by evert** [comment]
So, there's a miscommunication here. This ticket was about disabling `CHARSET` for every format _except_ vCard 2.1.

Any issues with charset that _do_ target vCard 2.1 are valid. The idea with supporting different charsets was to not just add any possible charset we can think of, but rather only add support for the ones that actually occur 'in the wild'.

The bottom line is: if you see a lowercase `utf-8` in vCard 2.1, we should add support for it. So this a new feature request ;)

**Comment by PHPGangsta** [comment]
I also need the feature request, lowercase utf-8 CHARSET for vCard 2.1 ;)

This reduced/redacted vcf file is from Yahoo:
```
BEGIN:VCARD
VERSION:2.1
SOURCE:Yahoo Contacts (http://contacts.yahoo.com)
PRODID:-//Yahoo/Contacts/YAB3/2017
FN;CHARSET=utf-8:Test
N;CHARSET=utf-8:;Test2;;;
EMAIL;INTERNET;PREF;CHARSET=utf-8:test@test.de
UID;CHARSET=utf-8:07371dc9262a3eb457910d4375d8aa58
X-CID;CHARSET=utf-8:200
X-CREATED;CHARSET=utf-8:1454497086
X-MODIFIED;CHARSET=utf-8:1493525644
X-PRIMARY-PHONE;CHARSET=utf-8:0
END:VCARD
```

I'm getting
```Uncaught Sabre\VObject\ParseException: Unsupported CHARSET: utf-8```

A strtolower() in the switch-condition, and changing all case-values to lowercase, would fix the problem I guess:
https://github.com/sabre-io/vobject/blob/master/lib/Parser/MimeDir.php#L467
