### ISSUE TITLE
Floating dates considered UTC

### ISSUE THREAD

**Issue by jpirkey** [fruux/sabre-vobject#314]
```php
// Test Feed
$feed = <<<EVENT
BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
X-WR-CALNAME: All Events
X-WR-TIMEZONE:Australia/Queensland
BEGIN:VEVENT
UID:37881-218695302-20150904032136@tave.com
DTSTAMP:20160411T130026Z
ATTENDEE;PARTSTAT=ACCEPTED;CN=Joe Smith:MAILTO:noname@gmail.com
CREATED:20150904T032136Z
DESCRIPTION:Test Event
DTSTART:20150314T100000
DTEND:20150314T150000
LAST-MODIFIED:20150904T032136Z
STATUS:CONFIRMED
SUMMARY:Joe Smith's Test Event
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
EVENT;

// Main
$cal = Sabre\VObject\Reader::read($feed);
$cal = $cal->expand(new DateTime('-2 years'), new DateTime('+5 years'));
$vevent = current($cal->select('VEVENT'));
return [
 $vevent->DTSTART->getDateTime(),
 $vevent->DTSTART->isFloating()
];
```

If you look in `DateTimeParser::parseDateTime` ... `$dt` is passed in as `20150314T100000Z` when it shouldn't be from `Sabre\VObject\Property\ICalendar\DateTime->getDateTimes(null)` so `DateTime->isFloating` always returns `false`; when, in this case, it should return true

Not sure this is related to #248 or not.

**Comment by evert** [comment]
The reason for this is that when you call `expand()` we basically fall all the rules of CalDAV recurrence expansion. One of those rules is that we must strip all timezone information, and we must convert all dates and times to UTC.

By default we assume that all floating dates and times are rooted in UTC, but: when you call `expand()` you can pass a third parameter, which is a reference timezone. In your case you might pass `Australia/Queensland` so that all floating times will be assumed to be in that tz before converted to UTC.

Hope this helps!

**Comment by jpirkey** [comment]
Perfect! Thanks @evert !
